#!/usr/bin/env python3
"""Generate the support matrix from profiles and their release manifests/ledgers."""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from omp_strata.receipts import gate_inventory
from omp_strata.profile import load_route
from scripts.verify_release import verify

GATES = tuple(gate_inventory())                     # the execution packet's canonical gate ids, in order
OUTCOMES = {"pass", "fail", "blocked", "not_run", "not_applicable"}


def cell(value: object) -> str:
    return str(value).replace("&", "&amp;").replace("|", "&#124;").replace("\n", " ").replace("\r", " ")


def release_state(root: Path, pid: str) -> tuple[str, str, dict[str, str]]:
    release = root / "releases" / pid
    manifest_path = release / "manifest.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8")) if manifest_path.exists() else None
    ledger_path = release / "qualification.json"
    ledger = json.loads(ledger_path.read_text(encoding="utf-8")) if ledger_path.exists() else None
    gates = {}
    for gate in ledger["gates"] if ledger is not None else []:
        gid, outcome = gate["id"], gate["status"]
        if gid not in GATES or gid in gates or outcome not in OUTCOMES:
            raise ValueError(f"{pid}: invalid or duplicate gate record")
        gates[gid] = outcome
    qualified = manifest is not None and not verify(manifest_path, require_ready=True)["errors"]
    return manifest["status"] if manifest is not None else "missing", "yes" if qualified else "no", gates


def render(root: Path = ROOT) -> str:
    """Display recorded outcomes, never promote them; readiness delegates to the verifier."""
    header = ["Profile id", "GPU", "Strata", "OMP", "Model variant / quantization", "Configured context",
              "Low-RAM mode", "Manifest status", "Qualified", *GATES]
    lines = [
        "<!-- Generated by scripts/render_compatibility.py; do not edit. -->",
        "# Compatibility matrix", "",
        "Source of truth: `profiles/*.json`, `routes/*.json` and `releases/<id>/{manifest,qualification}.json`.",
        "One row per server profile or client route, sorted by id within each table.",
        "No separate support-status database is maintained.", "",
        "**Qualified** is yes only when `scripts.verify_release.verify(..., require_ready=True)` returns",
        "no errors, including its receipt/hash checks. A draft, blocked gate, or host-free proof alone",
        "does not qualify a GPU route. Manifest status and gate outcomes below are recorded values,",
        "not inferred support claims. `missing` means no manifest, ledger or gate record exists;",
        "it is not silently converted to `not_run`. Invalid recorded outcomes stop generation.", "",
        f"{GATES[0]}–{GATES[-1]} retain `pass`, `fail`, `blocked`, `not_run` or `not_applicable` exactly as recorded.",
        "Historical failures remain in the ledgers' receipt histories even if a later run passed.",
        "See [operations](OPERATIONS.md), [upstream findings](UPSTREAM.md) and",
        "[troubleshooting](TROUBLESHOOTING.md) before using an unqualified profile.", "",
        "Regenerate: `python3 scripts/render_compatibility.py`; freshness: append `--check`.", "",
        "| " + " | ".join(header) + " |",
        "| " + " | ".join("---" for _ in header) + " |",
    ]
    profiles = [json.loads(path.read_text(encoding="utf-8")) for path in sorted((root / "profiles").glob("*.json"))]
    seen = set()
    for profile in sorted(profiles, key=lambda p: p["profile_id"]):
        pid = profile["profile_id"]
        if pid in seen or Path(pid).name != pid or "/" in pid or "\\" in pid or pid in (".", ".."):
            raise ValueError("duplicate or unsafe profile id")
        seen.add(pid)
        status, qualified, gates = release_state(root, pid)
        setup = profile["strata"]["setup_args"]
        row = [pid, profile["host"]["gpu_model"], profile["strata"]["tag"], profile["omp"]["version"],
               profile["model"]["variant"] + " / " + profile["model"]["quantization"], setup["context"],
               setup["low_ram"], status, qualified, *(gates.get(gid, "missing") for gid in GATES)]
        lines.append("| " + " | ".join(cell(v) for v in row) + " |")
    routes = [load_route(path, profiles_dir=root / "profiles") for path in sorted((root / "routes").glob("*.json"))]
    route_rows = []
    route_gates = {"G23"}
    for route in sorted(routes, key=lambda r: r.id):
        if route.id in seen:
            raise ValueError("duplicate profile or route id")
        seen.add(route.id)
        status, qualified, gates = release_state(root, route.id)
        route_gates.update(gates)
        members = sorted(route.data["members"], key=lambda m: m["label"])
        shape = "single host" if len(members) == 1 else "fleet"
        row = [route.id, route.data["kind"] + " / " + shape, len(members),
               "; ".join(m["label"] + " → " + m["server_profile"] for m in members), status, qualified]
        route_rows.append((row, gates))
    gate_columns = ["G23", *sorted(route_gates - {"G23"})]
    route_header = ["Route id", "Kind / shape", "Members", "Member → server profile",
                    "Manifest status", "Qualified", *gate_columns]
    lines.extend(["", "## Client routes", "",
                  "Client routes are validated with `load_route`; they reference immutable server profiles,",
                  "not copies of GPU evidence. The current route schema declares no client-platform field;",
                  "platform support is not inferred from available OMP binaries. Route qualification uses",
                  "its own manifest and ledger. G23 is always shown, together with any other recorded gates;",
                  "absent records are `missing`. A route row does not qualify its member GPU installations.", "",
                  "| " + " | ".join(route_header) + " |",
                  "| " + " | ".join("---" for _ in route_header) + " |"])
    for row, gates in route_rows:
        lines.append("| " + " | ".join(cell(v) for v in [*row, *(gates.get(gid, "missing") for gid in gate_columns)]) + " |")
    return "\n".join(lines) + "\n"


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the generated document is stale; write nothing")
    parser.add_argument("--root", type=Path, default=ROOT, help="repository root")
    args = parser.parse_args(argv)
    try:
        expected = render(args.root).encode("utf-8")
        dest = args.root / "docs/COMPATIBILITY.md"
        if args.check:
            if not dest.is_file() or dest.read_bytes() != expected:
                print("docs/COMPATIBILITY.md is stale; run python3 scripts/render_compatibility.py", file=sys.stderr)
                return 1
            print("docs/COMPATIBILITY.md is current")
        else:
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_bytes(expected)
            print("Rendered docs/COMPATIBILITY.md")
    except (OSError, ValueError, KeyError, TypeError) as exc:
        print(f"Cannot render compatibility matrix ({type(exc).__name__})", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
