#!/usr/bin/env python3
"""Generate the support matrix from profiles and their release manifests/ledgers."""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from omp_strata.receipts import gate_inventory
from scripts.verify_release import verify

GATES = tuple(gate_inventory())                     # the execution packet's canonical gate ids, in order
OUTCOMES = {"pass", "fail", "blocked", "not_run", "not_applicable"}


def cell(value: object) -> str:
    return str(value).replace("&", "&amp;").replace("|", "&#124;").replace("\n", " ").replace("\r", " ")


def render(root: Path = ROOT) -> str:
    """Display recorded outcomes, never promote them; readiness delegates to the verifier."""
    header = ["Profile id", "GPU", "Strata", "OMP", "Model variant / quantization", "Configured context",
              "Low-RAM mode", "Manifest status", "Qualified", *GATES]
    lines = [
        "<!-- Generated by scripts/render_compatibility.py; do not edit. -->",
        "# Compatibility matrix", "",
        "Source of truth: `profiles/*.json` and `releases/<profile>/{manifest,qualification}.json`.",
        "One row per profile, sorted by id. No separate support-status database is maintained.", "",
        "**Qualified** is yes only when `scripts.verify_release.verify(..., require_ready=True)` returns",
        "no errors, including its receipt/hash checks. A draft, blocked gate, or host-free proof alone",
        "does not qualify a GPU route. Manifest status and gate outcomes below are recorded values,",
        "not inferred support claims. `missing` means no manifest, ledger or gate record exists;",
        "it is not silently converted to `not_run`. Invalid recorded outcomes stop generation.", "",
        f"{GATES[0]}–{GATES[-1]} retain `pass`, `fail`, `blocked`, `not_run` or `not_applicable` exactly as recorded.",
        "Historical failures remain in the ledgers' receipt histories even if a later run passed.",
        "See [operations](OPERATIONS.md), [upstream findings](UPSTREAM.md) and",
        "[troubleshooting](TROUBLESHOOTING.md) before using an unqualified profile.", "",
        "Regenerate: `python3 scripts/render_compatibility.py`; freshness: append `--check`.", "",
        "| " + " | ".join(header) + " |",
        "| " + " | ".join("---" for _ in header) + " |",
    ]
    profiles = [json.loads(path.read_text(encoding="utf-8")) for path in sorted((root / "profiles").glob("*.json"))]
    seen = set()
    for profile in sorted(profiles, key=lambda p: p["profile_id"]):
        pid = profile["profile_id"]
        if pid in seen or Path(pid).name != pid or "/" in pid or "\\" in pid or pid in (".", ".."):
            raise ValueError("duplicate or unsafe profile id")
        seen.add(pid)
        release = root / "releases" / pid
        manifest_path = release / "manifest.json"
        manifest = json.loads(manifest_path.read_text(encoding="utf-8")) if manifest_path.exists() else None
        ledger_path = release / "qualification.json"
        ledger = json.loads(ledger_path.read_text(encoding="utf-8")) if ledger_path.exists() else None
        gates = {}
        for gate in ledger["gates"] if ledger is not None else []:
            gid, outcome = gate["id"], gate["status"]
            if gid not in GATES or gid in gates or outcome not in OUTCOMES:
                raise ValueError(f"{pid}: invalid or duplicate gate record")
            gates[gid] = outcome
        qualified = manifest is not None and not verify(manifest_path, require_ready=True)["errors"]
        setup = profile["strata"]["setup_args"]
        row = [pid, profile["host"]["gpu_model"], profile["strata"]["tag"], profile["omp"]["version"],
               profile["model"]["variant"] + " / " + profile["model"]["quantization"], setup["context"],
               setup["low_ram"], manifest["status"] if manifest is not None else "missing",
               "yes" if qualified else "no", *(gates.get(gid, "missing") for gid in GATES)]
        lines.append("| " + " | ".join(cell(v) for v in row) + " |")
    return "\n".join(lines) + "\n"


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the generated document is stale; write nothing")
    parser.add_argument("--root", type=Path, default=ROOT, help="repository root")
    args = parser.parse_args(argv)
    try:
        expected = render(args.root).encode("utf-8")
        dest = args.root / "docs/COMPATIBILITY.md"
        if args.check:
            if not dest.is_file() or dest.read_bytes() != expected:
                print("docs/COMPATIBILITY.md is stale; run python3 scripts/render_compatibility.py", file=sys.stderr)
                return 1
            print("docs/COMPATIBILITY.md is current")
        else:
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_bytes(expected)
            print("Rendered docs/COMPATIBILITY.md")
    except (OSError, ValueError, KeyError, TypeError) as exc:
        print(f"Cannot render compatibility matrix ({type(exc).__name__})", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
